### ISSUE TITLE
can you pls provide pre-trained data?

### ISSUE THREAD

**Issue by nvcken** [kiwonum/mlflip#1]

**Comment by kiwonum** [comment]
Which one do you mean? A pre-trained model or training data set?
The former has been already provided in the scene folder.
For the latter, weren't you able to run the provided scripts for training data generation? If you have any problems to run them, I guess you might see the same problems when running MLFLIP.

**Comment by nvcken** [comment]
I'm not sure about MantaFlow, has anyway to install MantaFlow instead build it from source on MacOS?

**Comment by kiwonum** [comment]
Unfortunately not. Please refer to http://mantaflow.com/install.html#osx
